### PR TITLE
Fix cards assertions

### PR DESCRIPTION
**Pull request by wfeller**
Cards don't use `uriKey()` but `component()` instead.

### CODE REVIEW

**Comment by wfeller** [comment]
Hey @dillingham,

Mind merging this please?

Thanks.

**Comment by andresilvagomez** [comment]
@dillingham im testing it but i think is not OK

**Comment by andresilvagomez** [comment]
each time returns 'confirm-action-modal'

**Comment by dillingham** [comment]
@andresilvagomez cards don't have uriKeys though.

I am pulling this down to test, I released "BETA" cause I wasnt 100%

**Comment by andresilvagomez** [comment]
@dillingham sorry that's trueee I was watching actions !!!

**Comment by dillingham** [comment]
@andresilvagomez no worries :) thanks for checking though

**Pull request merged**
